package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.CustomerAddr;
import com.zstu.tbmg.pojo.CustomerAddrExample;
import java.util.List;

public interface CustomerAddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int deleteByPrimaryKey(Integer customerAddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int insert(CustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int insertSelective(CustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    List<CustomerAddr> selectByExample(CustomerAddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    CustomerAddr selectByPrimaryKey(Integer customerAddrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int updateByPrimaryKeySelective(CustomerAddr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_addr
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int updateByPrimaryKey(CustomerAddr record);
}