package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.CustomerInf;
import com.zstu.tbmg.pojo.CustomerInfExample;
import java.util.List;

public interface CustomerInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int deleteByPrimaryKey(Integer customerInfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int insert(CustomerInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int insertSelective(CustomerInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    List<CustomerInf> selectByExample(CustomerInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    CustomerInf selectByPrimaryKey(Integer customerInfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int updateByPrimaryKeySelective(CustomerInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_inf
     *
     * @mbg.generated 2021-01-08 16:29:21
     */
    int updateByPrimaryKey(CustomerInf record);
}