package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.CustomerMaster;
import com.zstu.tbmg.pojo.CustomerMasterExample;
import java.util.List;

public interface CustomerMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_master
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    int insert(CustomerMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_master
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    int insertSelective(CustomerMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_master
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    List<CustomerMaster> selectByExample(CustomerMasterExample example);
}