package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.CustomerLogin;
import com.zstu.tbmg.pojo.CustomerLoginExample;

import java.util.List;

public interface CustomerLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    int insert(CustomerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    int insertSelective(CustomerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    List<CustomerLogin> selectByExample(CustomerLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    CustomerLogin selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    int updateByPrimaryKeySelective(CustomerLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_login
     *
     * @mbg.generated 2020-10-16 19:50:24
     */
    int updateByPrimaryKey(CustomerLogin record);
}