package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.ManagerInf;
import com.zstu.tbmg.pojo.ManagerInfExample;
import java.util.List;

public interface ManagerInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    int deleteByPrimaryKey(Integer managerInfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    int insert(ManagerInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    int insertSelective(ManagerInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    List<ManagerInf> selectByExample(ManagerInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    ManagerInf selectByPrimaryKey(Integer managerInfId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    int updateByPrimaryKeySelective(ManagerInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    int updateByPrimaryKey(ManagerInf record);
}