package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.OrderSmall;
import com.zstu.tbmg.pojo.OrderSmallExample;
import java.util.List;

public interface OrderSmallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_small
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int insert(OrderSmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_small
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int insertSelective(OrderSmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_small
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    List<OrderSmall> selectByExample(OrderSmallExample example);
}