package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.OrderDetail;
import com.zstu.tbmg.pojo.OrderDetailExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int deleteByPrimaryKey(Integer orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    OrderDetail selectByPrimaryKey(Integer orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    int updateByPrimaryKey(OrderDetail record);

//    @Update("update order_detail set shipping_comp_name=#{},shipping_sn={},shipping_time=now() where order_detail_id = #{orderDetailId}")
//    void updateById(@Param(""))
}