package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.ProductPicInfo;

public interface ProductPicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int deleteByPrimaryKey(Integer productPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int insert(ProductPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int insertSelective(ProductPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    ProductPicInfo selectByPrimaryKey(Integer productPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int updateByPrimaryKeySelective(ProductPicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int updateByPrimaryKey(ProductPicInfo record);
}