package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.ProductSupplierInfo;

public interface ProductSupplierInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_supplier_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int deleteByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_supplier_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int insert(ProductSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_supplier_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int insertSelective(ProductSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_supplier_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    ProductSupplierInfo selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_supplier_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int updateByPrimaryKeySelective(ProductSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_supplier_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    int updateByPrimaryKey(ProductSupplierInfo record);
}