package com.zstu.tbmg.mapper.db2;

import com.zstu.tbmg.pojo.WareHouseProduct;

public interface WareHouseProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    int deleteByPrimaryKey(Integer warehouseProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    int insert(WareHouseProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    int insertSelective(WareHouseProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    WareHouseProduct selectByPrimaryKey(Integer warehouseProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    int updateByPrimaryKeySelective(WareHouseProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    int updateByPrimaryKey(WareHouseProduct record);
}