package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_master
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-08 14:16:53
 */
public class CustomerMaster implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_master.customer_id
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private Integer customerId;

    /**
     * Database Column Remarks:
     *   用户登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_master.login_name
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   用户真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_master.customer_name
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_master.customer_email
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private String customerEmail;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_master.register_time
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private Date registerTime;

    /**
     * Database Column Remarks:
     *   用户状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_master.user_stats
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private Byte userStats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_master
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_master.customer_id
     *
     * @return the value of customer_master.customer_id
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_master.customer_id
     *
     * @param customerId the value for customer_master.customer_id
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_master.login_name
     *
     * @return the value of customer_master.login_name
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_master.login_name
     *
     * @param loginName the value for customer_master.login_name
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_master.customer_name
     *
     * @return the value of customer_master.customer_name
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_master.customer_name
     *
     * @param customerName the value for customer_master.customer_name
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_master.customer_email
     *
     * @return the value of customer_master.customer_email
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_master.customer_email
     *
     * @param customerEmail the value for customer_master.customer_email
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_master.register_time
     *
     * @return the value of customer_master.register_time
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_master.register_time
     *
     * @param registerTime the value for customer_master.register_time
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_master.user_stats
     *
     * @return the value of customer_master.user_stats
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public Byte getUserStats() {
        return userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_master.user_stats
     *
     * @param userStats the value for customer_master.user_stats
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    public void setUserStats(Byte userStats) {
        this.userStats = userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_master
     *
     * @mbg.generated 2021-01-08 14:16:53
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", loginName=").append(loginName);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerEmail=").append(customerEmail);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", userStats=").append(userStats);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}