package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   管理员登陆日志表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table manager_login_log
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-05 15:09:42
 */
public class ManagerLoginLog implements Serializable {
    /**
     * Database Column Remarks:
     *   登陆日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login_log.login_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Integer loginId;

    /**
     * Database Column Remarks:
     *   登陆管理员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login_log.manager_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Integer managerId;

    /**
     * Database Column Remarks:
     *   管理员登陆时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login_log.login_time
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Date loginTime;

    /**
     * Database Column Remarks:
     *   登陆IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login_log.login_ip
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Integer loginIp;

    /**
     * Database Column Remarks:
     *   登陆类型：0未成功，1成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login_log.login_type
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Byte loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_login_log
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login_log.login_id
     *
     * @return the value of manager_login_log.login_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login_log.login_id
     *
     * @param loginId the value for manager_login_log.login_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login_log.manager_id
     *
     * @return the value of manager_login_log.manager_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login_log.manager_id
     *
     * @param managerId the value for manager_login_log.manager_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login_log.login_time
     *
     * @return the value of manager_login_log.login_time
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login_log.login_time
     *
     * @param loginTime the value for manager_login_log.login_time
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login_log.login_ip
     *
     * @return the value of manager_login_log.login_ip
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Integer getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login_log.login_ip
     *
     * @param loginIp the value for manager_login_log.login_ip
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setLoginIp(Integer loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login_log.login_type
     *
     * @return the value of manager_login_log.login_type
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Byte getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login_log.login_type
     *
     * @param loginType the value for manager_login_log.login_type
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setLoginType(Byte loginType) {
        this.loginType = loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login_log
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", loginId=").append(loginId);
        sb.append(", managerId=").append(managerId);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", loginType=").append(loginType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}