package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   管理员登录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table manager_login
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-05 15:09:42
 */
public class ManagerLogin implements Serializable {
    /**
     * Database Column Remarks:
     *   管理员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login.manager_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Integer managerId;

    /**
     * Database Column Remarks:
     *   管理员登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login.login_name
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   md5加密的密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login.password
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private String password;

    /**
     * Database Column Remarks:
     *   用户状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login.user_stats
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Byte userStats;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_login.modified_time
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_login
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login.manager_id
     *
     * @return the value of manager_login.manager_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login.manager_id
     *
     * @param managerId the value for manager_login.manager_id
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login.login_name
     *
     * @return the value of manager_login.login_name
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login.login_name
     *
     * @param loginName the value for manager_login.login_name
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login.password
     *
     * @return the value of manager_login.password
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login.password
     *
     * @param password the value for manager_login.password
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login.user_stats
     *
     * @return the value of manager_login.user_stats
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Byte getUserStats() {
        return userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login.user_stats
     *
     * @param userStats the value for manager_login.user_stats
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setUserStats(Byte userStats) {
        this.userStats = userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_login.modified_time
     *
     * @return the value of manager_login.modified_time
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_login.modified_time
     *
     * @param modifiedTime the value for manager_login.modified_time
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_login
     *
     * @mbg.generated 2021-01-05 15:09:42
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", managerId=").append(managerId);
        sb.append(", loginName=").append(loginName);
        sb.append(", password=").append(password);
        sb.append(", userStats=").append(userStats);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}