package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   管理员信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table manager_inf
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-08 15:17:35
 */
public class ManagerInf implements Serializable {
    /**
     * Database Column Remarks:
     *   管理员信息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_inf.manager_inf_id
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private Integer managerInfId;

    /**
     * Database Column Remarks:
     *   username
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_inf.login_name
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   管理员名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_inf.manager_name
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private String managerName;

    /**
     * Database Column Remarks:
     *   email
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_inf.manager_email
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private String managerEmail;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_inf.modified_time
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private Date modifiedTime;

    /**
     * Database Column Remarks:
     *   注册时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_inf.register_time
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private Date registerTime;

    private Byte userStats;

    public Byte getUserStats() {
        return userStats;
    }

    public void setUserStats(Byte userStats) {
        this.userStats = userStats;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_inf.manager_inf_id
     *
     * @return the value of manager_inf.manager_inf_id
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public Integer getManagerInfId() {
        return managerInfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_inf.manager_inf_id
     *
     * @param managerInfId the value for manager_inf.manager_inf_id
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public void setManagerInfId(Integer managerInfId) {
        this.managerInfId = managerInfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_inf.login_name
     *
     * @return the value of manager_inf.login_name
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_inf.login_name
     *
     * @param loginName the value for manager_inf.login_name
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_inf.manager_name
     *
     * @return the value of manager_inf.manager_name
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_inf.manager_name
     *
     * @param managerName the value for manager_inf.manager_name
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_inf.manager_email
     *
     * @return the value of manager_inf.manager_email
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public String getManagerEmail() {
        return managerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_inf.manager_email
     *
     * @param managerEmail the value for manager_inf.manager_email
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public void setManagerEmail(String managerEmail) {
        this.managerEmail = managerEmail == null ? null : managerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_inf.modified_time
     *
     * @return the value of manager_inf.modified_time
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_inf.modified_time
     *
     * @param modifiedTime the value for manager_inf.modified_time
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_inf.register_time
     *
     * @return the value of manager_inf.register_time
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_inf.register_time
     *
     * @param registerTime the value for manager_inf.register_time
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_inf
     *
     * @mbg.generated 2021-01-08 15:17:35
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", managerInfId=").append(managerInfId);
        sb.append(", loginName=").append(loginName);
        sb.append(", managerName=").append(managerName);
        sb.append(", managerEmail=").append(managerEmail);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}