package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_small
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 21:23:46
 */
public class OrderSmall implements Serializable {
    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Integer orderDetailId;

    /**
     * Database Column Remarks:
     *   订单编号 yyyymmddnnnnnnnn
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.order_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Long orderSn;

    /**
     * Database Column Remarks:
     *   下单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.create_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   用户登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.login_name
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   订单金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.order_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private BigDecimal orderMoney;

    /**
     * Database Column Remarks:
     *   订单状态 0为关闭，1为已支付，2为已发货，.....
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.order_status
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Byte orderStatus;

    /**
     * Database Column Remarks:
     *   支付方式：1现金，2余额，3网银，4支付宝，5微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_small.payment_method
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Byte paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_small
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.order_detail_id
     *
     * @return the value of order_small.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.order_detail_id
     *
     * @param orderDetailId the value for order_small.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.order_sn
     *
     * @return the value of order_small.order_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Long getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.order_sn
     *
     * @param orderSn the value for order_small.order_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.create_time
     *
     * @return the value of order_small.create_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.create_time
     *
     * @param createTime the value for order_small.create_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.login_name
     *
     * @return the value of order_small.login_name
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.login_name
     *
     * @param loginName the value for order_small.login_name
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.order_money
     *
     * @return the value of order_small.order_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.order_money
     *
     * @param orderMoney the value for order_small.order_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.order_status
     *
     * @return the value of order_small.order_status
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.order_status
     *
     * @param orderStatus the value for order_small.order_status
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_small.payment_method
     *
     * @return the value of order_small.payment_method
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_small.payment_method
     *
     * @param paymentMethod the value for order_small.payment_method
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_small
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", loginName=").append(loginName);
        sb.append(", orderMoney=").append(orderMoney);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}