package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   订单细节表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_detail
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 21:23:46
 */
public class OrderDetail implements Serializable {
    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Integer orderDetailId;

    /**
     * Database Column Remarks:
     *   订单编号 yyyymmddnnnnnnnn
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Long orderSn;

    /**
     * Database Column Remarks:
     *   下单人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.customer_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Integer customerId;

    /**
     * Database Column Remarks:
     *   收货人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.shipping_user
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String shippingUser;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.province
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.city
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.district
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String district;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.address
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String address;

    /**
     * Database Column Remarks:
     *   支付方式：1现金，2余额，3网银，4支付宝，5微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.payment_method
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Byte paymentMethod;

    /**
     * Database Column Remarks:
     *   订单金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private BigDecimal orderMoney;

    /**
     * Database Column Remarks:
     *   优惠金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.coupon_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private BigDecimal couponMoney;

    /**
     * Database Column Remarks:
     *   运费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.shipping_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private BigDecimal shippingMoney;

    /**
     * Database Column Remarks:
     *   支付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.payment_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private BigDecimal paymentMoney;

    /**
     * Database Column Remarks:
     *   快递公司名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.shipping_comp_name
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String shippingCompName;

    /**
     * Database Column Remarks:
     *   快递单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.shipping_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String shippingSn;

    /**
     * Database Column Remarks:
     *   下单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.create_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.shipping_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Date shippingTime;

    /**
     * Database Column Remarks:
     *   支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.pay_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Date payTime;

    /**
     * Database Column Remarks:
     *   收货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.receive_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Date receiveTime;

    /**
     * Database Column Remarks:
     *   订单状态 0为关闭，1为已支付，2为已发货，.....
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_status
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Byte orderStatus;

    /**
     * Database Column Remarks:
     *   订单积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_point
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Integer orderPoint;

    /**
     * Database Column Remarks:
     *   发票抬头
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.invoice_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private String invoiceTime;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.modified_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_detail_id
     *
     * @return the value of order_detail.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_detail_id
     *
     * @param orderDetailId the value for order_detail.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_sn
     *
     * @return the value of order_detail.order_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Long getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_sn
     *
     * @param orderSn the value for order_detail.order_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.customer_id
     *
     * @return the value of order_detail.customer_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.customer_id
     *
     * @param customerId the value for order_detail.customer_id
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.shipping_user
     *
     * @return the value of order_detail.shipping_user
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getShippingUser() {
        return shippingUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.shipping_user
     *
     * @param shippingUser the value for order_detail.shipping_user
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setShippingUser(String shippingUser) {
        this.shippingUser = shippingUser == null ? null : shippingUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.province
     *
     * @return the value of order_detail.province
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.province
     *
     * @param province the value for order_detail.province
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.city
     *
     * @return the value of order_detail.city
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.city
     *
     * @param city the value for order_detail.city
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.district
     *
     * @return the value of order_detail.district
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.district
     *
     * @param district the value for order_detail.district
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.address
     *
     * @return the value of order_detail.address
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.address
     *
     * @param address the value for order_detail.address
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.payment_method
     *
     * @return the value of order_detail.payment_method
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.payment_method
     *
     * @param paymentMethod the value for order_detail.payment_method
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_money
     *
     * @return the value of order_detail.order_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_money
     *
     * @param orderMoney the value for order_detail.order_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.coupon_money
     *
     * @return the value of order_detail.coupon_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public BigDecimal getCouponMoney() {
        return couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.coupon_money
     *
     * @param couponMoney the value for order_detail.coupon_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setCouponMoney(BigDecimal couponMoney) {
        this.couponMoney = couponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.shipping_money
     *
     * @return the value of order_detail.shipping_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public BigDecimal getShippingMoney() {
        return shippingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.shipping_money
     *
     * @param shippingMoney the value for order_detail.shipping_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setShippingMoney(BigDecimal shippingMoney) {
        this.shippingMoney = shippingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.payment_money
     *
     * @return the value of order_detail.payment_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public BigDecimal getPaymentMoney() {
        return paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.payment_money
     *
     * @param paymentMoney the value for order_detail.payment_money
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setPaymentMoney(BigDecimal paymentMoney) {
        this.paymentMoney = paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.shipping_comp_name
     *
     * @return the value of order_detail.shipping_comp_name
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getShippingCompName() {
        return shippingCompName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.shipping_comp_name
     *
     * @param shippingCompName the value for order_detail.shipping_comp_name
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setShippingCompName(String shippingCompName) {
        this.shippingCompName = shippingCompName == null ? null : shippingCompName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.shipping_sn
     *
     * @return the value of order_detail.shipping_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getShippingSn() {
        return shippingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.shipping_sn
     *
     * @param shippingSn the value for order_detail.shipping_sn
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setShippingSn(String shippingSn) {
        this.shippingSn = shippingSn == null ? null : shippingSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.create_time
     *
     * @return the value of order_detail.create_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.create_time
     *
     * @param createTime the value for order_detail.create_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.shipping_time
     *
     * @return the value of order_detail.shipping_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Date getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.shipping_time
     *
     * @param shippingTime the value for order_detail.shipping_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setShippingTime(Date shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.pay_time
     *
     * @return the value of order_detail.pay_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.pay_time
     *
     * @param payTime the value for order_detail.pay_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.receive_time
     *
     * @return the value of order_detail.receive_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.receive_time
     *
     * @param receiveTime the value for order_detail.receive_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_status
     *
     * @return the value of order_detail.order_status
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_status
     *
     * @param orderStatus the value for order_detail.order_status
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_point
     *
     * @return the value of order_detail.order_point
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Integer getOrderPoint() {
        return orderPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_point
     *
     * @param orderPoint the value for order_detail.order_point
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setOrderPoint(Integer orderPoint) {
        this.orderPoint = orderPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.invoice_time
     *
     * @return the value of order_detail.invoice_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public String getInvoiceTime() {
        return invoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.invoice_time
     *
     * @param invoiceTime the value for order_detail.invoice_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setInvoiceTime(String invoiceTime) {
        this.invoiceTime = invoiceTime == null ? null : invoiceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.modified_time
     *
     * @return the value of order_detail.modified_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.modified_time
     *
     * @param modifiedTime the value for order_detail.modified_time
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbg.generated 2021-01-07 21:23:46
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", customerId=").append(customerId);
        sb.append(", shippingUser=").append(shippingUser);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", address=").append(address);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", orderMoney=").append(orderMoney);
        sb.append(", couponMoney=").append(couponMoney);
        sb.append(", shippingMoney=").append(shippingMoney);
        sb.append(", paymentMoney=").append(paymentMoney);
        sb.append(", shippingCompName=").append(shippingCompName);
        sb.append(", shippingSn=").append(shippingSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", shippingTime=").append(shippingTime);
        sb.append(", payTime=").append(payTime);
        sb.append(", receiveTime=").append(receiveTime);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderPoint=").append(orderPoint);
        sb.append(", invoiceTime=").append(invoiceTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}