package com.zstu.tbmg.pojo;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   VIEW
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_shipping_info
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 21:59:06
 */
public class OrderShippingInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_info.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    private Integer orderDetailId;

    /**
     * Database Column Remarks:
     *   订单编号 yyyymmddnnnnnnnn
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_info.order_sn
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    private Long orderSn;

    /**
     * Database Column Remarks:
     *   用户登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_info.login_name
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_info.mobile_phone
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping_info.address
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_shipping_info
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_info.order_detail_id
     *
     * @return the value of order_shipping_info.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_info.order_detail_id
     *
     * @param orderDetailId the value for order_shipping_info.order_detail_id
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_info.order_sn
     *
     * @return the value of order_shipping_info.order_sn
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public Long getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_info.order_sn
     *
     * @param orderSn the value for order_shipping_info.order_sn
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_info.login_name
     *
     * @return the value of order_shipping_info.login_name
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_info.login_name
     *
     * @param loginName the value for order_shipping_info.login_name
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_info.mobile_phone
     *
     * @return the value of order_shipping_info.mobile_phone
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_info.mobile_phone
     *
     * @param mobilePhone the value for order_shipping_info.mobile_phone
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping_info.address
     *
     * @return the value of order_shipping_info.address
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping_info.address
     *
     * @param address the value for order_shipping_info.address
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_shipping_info
     *
     * @mbg.generated 2021-01-07 21:59:06
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", loginName=").append(loginName);
        sb.append(", mobilePhone=").append(mobilePhone);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}