package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品分类表，分类id是自关联的，父级分类和自己分类通过id指向。请不要占用id=0的分类id
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_category
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-06 13:12:18
 */
public class ProductCategory implements Serializable {
    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_name
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String categoryName;

    /**
     * Database Column Remarks:
     *   分类编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_code
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String categoryCode;

    /**
     * Database Column Remarks:
     *   父分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.parent_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   分类层级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_level
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Byte categoryLevel;

    /**
     * Database Column Remarks:
     *   分类状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.category_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Byte categoryStatus;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.modified_time
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_category
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_id
     *
     * @return the value of product_category.category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_id
     *
     * @param categoryId the value for product_category.category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_name
     *
     * @return the value of product_category.category_name
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_name
     *
     * @param categoryName the value for product_category.category_name
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_code
     *
     * @return the value of product_category.category_code
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_code
     *
     * @param categoryCode the value for product_category.category_code
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode == null ? null : categoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.parent_id
     *
     * @return the value of product_category.parent_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.parent_id
     *
     * @param parentId the value for product_category.parent_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_level
     *
     * @return the value of product_category.category_level
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Byte getCategoryLevel() {
        return categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_level
     *
     * @param categoryLevel the value for product_category.category_level
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setCategoryLevel(Byte categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.category_status
     *
     * @return the value of product_category.category_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Byte getCategoryStatus() {
        return categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.category_status
     *
     * @param categoryStatus the value for product_category.category_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setCategoryStatus(Byte categoryStatus) {
        this.categoryStatus = categoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.modified_time
     *
     * @return the value of product_category.modified_time
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.modified_time
     *
     * @param modifiedTime the value for product_category.modified_time
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", categoryName=").append(categoryName);
        sb.append(", categoryCode=").append(categoryCode);
        sb.append(", parentId=").append(parentId);
        sb.append(", categoryLevel=").append(categoryLevel);
        sb.append(", categoryStatus=").append(categoryStatus);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}