package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_info
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-06 13:12:18
 */
public class ProductInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   商品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_core
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String productCore;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   国条码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.bar_code
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String barCode;

    /**
     * Database Column Remarks:
     *   品牌表的ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.brand_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer brandId;

    /**
     * Database Column Remarks:
     *   一级分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.one_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer oneCategoryId;

    /**
     * Database Column Remarks:
     *   二级分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.two_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer twoCategoryId;

    /**
     * Database Column Remarks:
     *   三级分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.three_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer threeCategoryId;

    /**
     * Database Column Remarks:
     *   商品的供应商ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.supplier_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer supplierId;

    /**
     * Database Column Remarks:
     *   商品销售价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   商品加权平均成本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.average_cost
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private BigDecimal averageCost;

    /**
     * Database Column Remarks:
     *   上下架状态：0下架1上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.publish_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Byte publishStatus;

    /**
     * Database Column Remarks:
     *   审核状态：0未审核，1已审核
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.audit_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Byte auditStatus;

    /**
     * Database Column Remarks:
     *   商品重量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.weight
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Float weight;

    /**
     * Database Column Remarks:
     *   商品长度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.length
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Float length;

    /**
     * Database Column Remarks:
     *   商品高度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.height
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Float height;

    /**
     * Database Column Remarks:
     *   商品宽度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.width
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Float width;

    /**
     * Database Column Remarks:
     *   十六进制web颜色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.color
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String color;

    /**
     * Database Column Remarks:
     *   生产日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.production_date
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Date productionDate;

    /**
     * Database Column Remarks:
     *   商品有效期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.shelf_life
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Integer shelfLife;

    /**
     * Database Column Remarks:
     *   商品录入时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.indate
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Date indate;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.modified_time
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private Date modifiedTime;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.descript
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String descript;
    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.descript
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private String pic;

    private Integer sellNum;

    private Integer stockNum;

    private String wareHouse;

    private Integer productAmount;

    public Integer getProductAmount() {
        return productAmount;
    }

    public void setProductAmount(Integer productAmount) {
        this.productAmount = productAmount;
    }

    public String getWareHouse() {
        return wareHouse;
    }

    public void setWareHouse(String wareHouse) {
        this.wareHouse = wareHouse;
    }

    public Integer getSellNum() {
        return sellNum;
    }

    public void setSellNum(Integer sellNum) {
        this.sellNum = sellNum;
    }

    public Integer getStockNum() {
        return stockNum;
    }

    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_id
     *
     * @return the value of product_info.product_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_id
     *
     * @param productId the value for product_info.product_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_core
     *
     * @return the value of product_info.product_core
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getProductCore() {
        return productCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_core
     *
     * @param productCore the value for product_info.product_core
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setProductCore(String productCore) {
        this.productCore = productCore == null ? null : productCore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.bar_code
     *
     * @return the value of product_info.bar_code
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.bar_code
     *
     * @param barCode the value for product_info.bar_code
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.brand_id
     *
     * @return the value of product_info.brand_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.brand_id
     *
     * @param brandId the value for product_info.brand_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.one_category_id
     *
     * @return the value of product_info.one_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getOneCategoryId() {
        return oneCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.one_category_id
     *
     * @param oneCategoryId the value for product_info.one_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setOneCategoryId(Integer oneCategoryId) {
        this.oneCategoryId = oneCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.two_category_id
     *
     * @return the value of product_info.two_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getTwoCategoryId() {
        return twoCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.two_category_id
     *
     * @param twoCategoryId the value for product_info.two_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setTwoCategoryId(Integer twoCategoryId) {
        this.twoCategoryId = twoCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.three_category_id
     *
     * @return the value of product_info.three_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getThreeCategoryId() {
        return threeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.three_category_id
     *
     * @param threeCategoryId the value for product_info.three_category_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setThreeCategoryId(Integer threeCategoryId) {
        this.threeCategoryId = threeCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.supplier_id
     *
     * @return the value of product_info.supplier_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.supplier_id
     *
     * @param supplierId the value for product_info.supplier_id
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.price
     *
     * @return the value of product_info.price
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.price
     *
     * @param price the value for product_info.price
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.average_cost
     *
     * @return the value of product_info.average_cost
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public BigDecimal getAverageCost() {
        return averageCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.average_cost
     *
     * @param averageCost the value for product_info.average_cost
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setAverageCost(BigDecimal averageCost) {
        this.averageCost = averageCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.publish_status
     *
     * @return the value of product_info.publish_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Byte getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.publish_status
     *
     * @param publishStatus the value for product_info.publish_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setPublishStatus(Byte publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.audit_status
     *
     * @return the value of product_info.audit_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.audit_status
     *
     * @param auditStatus the value for product_info.audit_status
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.weight
     *
     * @return the value of product_info.weight
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.weight
     *
     * @param weight the value for product_info.weight
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.length
     *
     * @return the value of product_info.length
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.length
     *
     * @param length the value for product_info.length
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.height
     *
     * @return the value of product_info.height
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Float getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.height
     *
     * @param height the value for product_info.height
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setHeight(Float height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.width
     *
     * @return the value of product_info.width
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Float getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.width
     *
     * @param width the value for product_info.width
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setWidth(Float width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.color
     *
     * @return the value of product_info.color
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.color
     *
     * @param color the value for product_info.color
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.production_date
     *
     * @return the value of product_info.production_date
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.production_date
     *
     * @param productionDate the value for product_info.production_date
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.shelf_life
     *
     * @return the value of product_info.shelf_life
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Integer getShelfLife() {
        return shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.shelf_life
     *
     * @param shelfLife the value for product_info.shelf_life
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setShelfLife(Integer shelfLife) {
        this.shelfLife = shelfLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.indate
     *
     * @return the value of product_info.indate
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.indate
     *
     * @param indate the value for product_info.indate
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.modified_time
     *
     * @return the value of product_info.modified_time
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.modified_time
     *
     * @param modifiedTime the value for product_info.modified_time
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.descript
     *
     * @return the value of product_info.descript
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.descript
     *
     * @param descript the value for product_info.descript
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated 2021-01-06 13:12:18
     */
    @Override
    public String toString() {
        return "ProductInfo{" +
                "productId=" + productId +
                ", productCore='" + productCore + '\'' +
                ", productName='" + productName + '\'' +
                ", barCode='" + barCode + '\'' +
                ", brandId=" + brandId +
                ", oneCategoryId=" + oneCategoryId +
                ", twoCategoryId=" + twoCategoryId +
                ", threeCategoryId=" + threeCategoryId +
                ", supplierId=" + supplierId +
                ", price=" + price +
                ", averageCost=" + averageCost +
                ", publishStatus=" + publishStatus +
                ", auditStatus=" + auditStatus +
                ", weight=" + weight +
                ", length=" + length +
                ", height=" + height +
                ", width=" + width +
                ", color='" + color + '\'' +
                ", productionDate=" + productionDate +
                ", shelfLife=" + shelfLife +
                ", indate=" + indate +
                ", modifiedTime=" + modifiedTime +
                ", descript='" + descript + '\'' +
                ", pic='" + pic + '\'' +
                '}';
    }
}