package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   新品推荐表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_new_recommend
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 18:00:47
 */
public class ProductNewRecommend implements Serializable {
    /**
     * Database Column Remarks:
     *   推荐Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.new_recommend_id
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private Integer newRecommendId;

    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.product_id
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.product_name
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   图片URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.pic_url
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private String picUrl;

    /**
     * Database Column Remarks:
     *   是否推荐：0推荐1不推荐
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.recommend_status
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private Byte recommendStatus;

    /**
     * Database Column Remarks:
     *   是否为新品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.new_status
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private Byte newStatus;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.recommend_order
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private Byte recommendOrder;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_new_recommend.modified_time
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_new_recommend
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.new_recommend_id
     *
     * @return the value of product_new_recommend.new_recommend_id
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public Integer getNewRecommendId() {
        return newRecommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.new_recommend_id
     *
     * @param newRecommendId the value for product_new_recommend.new_recommend_id
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setNewRecommendId(Integer newRecommendId) {
        this.newRecommendId = newRecommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.product_id
     *
     * @return the value of product_new_recommend.product_id
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.product_id
     *
     * @param productId the value for product_new_recommend.product_id
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.product_name
     *
     * @return the value of product_new_recommend.product_name
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.product_name
     *
     * @param productName the value for product_new_recommend.product_name
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.pic_url
     *
     * @return the value of product_new_recommend.pic_url
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.pic_url
     *
     * @param picUrl the value for product_new_recommend.pic_url
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.recommend_status
     *
     * @return the value of product_new_recommend.recommend_status
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public Byte getRecommendStatus() {
        return recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.recommend_status
     *
     * @param recommendStatus the value for product_new_recommend.recommend_status
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setRecommendStatus(Byte recommendStatus) {
        this.recommendStatus = recommendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.new_status
     *
     * @return the value of product_new_recommend.new_status
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public Byte getNewStatus() {
        return newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.new_status
     *
     * @param newStatus the value for product_new_recommend.new_status
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setNewStatus(Byte newStatus) {
        this.newStatus = newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.recommend_order
     *
     * @return the value of product_new_recommend.recommend_order
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public Byte getRecommendOrder() {
        return recommendOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.recommend_order
     *
     * @param recommendOrder the value for product_new_recommend.recommend_order
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setRecommendOrder(Byte recommendOrder) {
        this.recommendOrder = recommendOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_new_recommend.modified_time
     *
     * @return the value of product_new_recommend.modified_time
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_new_recommend.modified_time
     *
     * @param modifiedTime the value for product_new_recommend.modified_time
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_new_recommend
     *
     * @mbg.generated 2021-01-07 18:00:47
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", newRecommendId=").append(newRecommendId);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", recommendStatus=").append(recommendStatus);
        sb.append(", newStatus=").append(newStatus);
        sb.append(", recommendOrder=").append(recommendOrder);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}