package com.zstu.tbmg.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品库存表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table warehouse_product
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 15:15:20
 */
public class WareHouseProduct implements Serializable {
    /**
     * Database Column Remarks:
     *   商品库存ID，此项不一定存在于product_info表的记录，因为“在库”和“上架”并非对等
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.warehouse_product_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private Integer warehouseProductId;

    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.product_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   仓库ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.warehouse_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private Integer warehouseId;

    /**
     * Database Column Remarks:
     *   当前商品数量，库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.current_cnt
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private Integer currentCnt;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.sell_cnt
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private Integer sellCnt;

    /**
     * Database Column Remarks:
     *   移动加权成本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.average_cost
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private BigDecimal averageCost;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_product.modified_time
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.warehouse_product_id
     *
     * @return the value of warehouse_product.warehouse_product_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public Integer getWarehouseProductId() {
        return warehouseProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.warehouse_product_id
     *
     * @param warehouseProductId the value for warehouse_product.warehouse_product_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setWarehouseProductId(Integer warehouseProductId) {
        this.warehouseProductId = warehouseProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.product_id
     *
     * @return the value of warehouse_product.product_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.product_id
     *
     * @param productId the value for warehouse_product.product_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.warehouse_id
     *
     * @return the value of warehouse_product.warehouse_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public Integer getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.warehouse_id
     *
     * @param warehouseId the value for warehouse_product.warehouse_id
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.current_cnt
     *
     * @return the value of warehouse_product.current_cnt
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public Integer getCurrentCnt() {
        return currentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.current_cnt
     *
     * @param currentCnt the value for warehouse_product.current_cnt
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setCurrentCnt(Integer currentCnt) {
        this.currentCnt = currentCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.sell_cnt
     *
     * @return the value of warehouse_product.sell_cnt
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public Integer getSellCnt() {
        return sellCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.sell_cnt
     *
     * @param sellCnt the value for warehouse_product.sell_cnt
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setSellCnt(Integer sellCnt) {
        this.sellCnt = sellCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.average_cost
     *
     * @return the value of warehouse_product.average_cost
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public BigDecimal getAverageCost() {
        return averageCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.average_cost
     *
     * @param averageCost the value for warehouse_product.average_cost
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setAverageCost(BigDecimal averageCost) {
        this.averageCost = averageCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_product.modified_time
     *
     * @return the value of warehouse_product.modified_time
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_product.modified_time
     *
     * @param modifiedTime the value for warehouse_product.modified_time
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_product
     *
     * @mbg.generated 2021-01-07 15:15:20
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", warehouseProductId=").append(warehouseProductId);
        sb.append(", productId=").append(productId);
        sb.append(", warehouseId=").append(warehouseId);
        sb.append(", currentCnt=").append(currentCnt);
        sb.append(", sellCnt=").append(sellCnt);
        sb.append(", averageCost=").append(averageCost);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}